services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: fox_survey
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build:
      context: ./app
      dockerfile: Dockerfile
    command: >
      bash -c "python manage.py migrate --noinput &&
               python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./app:/app
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      DJANGO_SECRET_KEY: "replace-this-in-prod"
      DJANGO_DEBUG: "True"
      DJANGO_ALLOWED_HOSTS: "localhost,127.0.0.1"
      POSTGRES_DB: fox_survey
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_HOST: db
      POSTGRES_PORT: "5432"

volumes:
  db_data:
