# Generated by Django 4.2.20 on 2025-05-01 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('camera_id', models.AutoField(primary_key=True, serialize=False)),
                ('model', models.CharField(max_length=100, verbose_name='Модель')),
                ('serial_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Серийный номер')),
                ('comments', models.TextField(blank=True, null=True, verbose_name='Комментарии')),
            ],
            options={
                'verbose_name': 'Фотоловушка',
                'verbose_name_plural': 'Фотоловушки',
            },
        ),
        migrations.CreateModel(
            name='ContactPerson',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Отчество')),
                ('team', models.CharField(blank=True, max_length=100, null=True, verbose_name='Команда')),
                ('contacts', models.TextField(verbose_name='Контактная информация')),
            ],
            options={
                'verbose_name': 'Контактное лицо',
                'verbose_name_plural': 'Контактные лица',
            },
        ),
        migrations.CreateModel(
            name='Fox',
            fields=[
                ('fox_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Имя/Идентификатор')),
                ('sex', models.CharField(choices=[('M', 'Самец'), ('F', 'Самка'), ('U', 'Неизвестно')], max_length=1, verbose_name='Пол')),
                ('age', models.PositiveIntegerField(blank=True, null=True, verbose_name='Возраст')),
                ('age_group', models.CharField(choices=[('CUB', 'Детеныш'), ('JUVENILE', 'Молодая особь'), ('ADULT', 'Взрослая особь'), ('SENIOR', 'Старая особь'), ('UNKNOWN', 'Неизвестно')], max_length=20, verbose_name='Возрастная группа')),
                ('group', models.CharField(blank=True, max_length=100, null=True, verbose_name='Группа')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Примечания')),
            ],
            options={
                'verbose_name': 'Лисица',
                'verbose_name_plural': 'Лисицы',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('name_of_location', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='Название местности')),
                ('longitude', models.FloatField(verbose_name='Долгота')),
                ('latitude', models.FloatField(verbose_name='Широта')),
                ('height', models.FloatField(blank=True, null=True, verbose_name='Высота')),
            ],
            options={
                'verbose_name': 'Местоположение',
                'verbose_name_plural': 'Местоположения',
            },
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('survey_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('season', models.CharField(blank=True, max_length=50, null=True, verbose_name='Сезон')),
                ('start_date', models.DateField(verbose_name='Дата начала')),
                ('end_date', models.DateField(verbose_name='Дата окончания')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Исследование',
                'verbose_name_plural': 'Исследования',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('image_id', models.AutoField(primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=255, verbose_name='Имя файла')),
                ('capture_date_time', models.DateTimeField(verbose_name='Дата и время съемки')),
                ('size', models.IntegerField(blank=True, null=True, verbose_name='Размер файла')),
                ('has_fox', models.BooleanField(default=False, verbose_name='Наличие лисицы')),
                ('image_file', models.ImageField(blank=True, null=True, upload_to='fox_images/', verbose_name='Файл изображения')),
                ('camera', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='foxapp.camera', verbose_name='Фотоловушка')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='foxapp.location', verbose_name='Местоположение')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='foxapp.survey', verbose_name='Исследование')),
            ],
            options={
                'verbose_name': 'Изображение',
                'verbose_name_plural': 'Изображения',
            },
        ),
        migrations.CreateModel(
            name='FoxImageInt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fox', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foxapp.fox', verbose_name='Лисица')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foxapp.image', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Связь лисица-изображение',
                'verbose_name_plural': 'Связи лисица-изображение',
                'unique_together': {('fox', 'image')},
            },
        ),
        migrations.AddField(
            model_name='fox',
            name='images',
            field=models.ManyToManyField(through='foxapp.FoxImageInt', to='foxapp.image', verbose_name='Изображения'),
        ),
        migrations.AddField(
            model_name='camera',
            name='contact_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='foxapp.contactperson', verbose_name='Контактное лицо'),
        ),
        migrations.AddField(
            model_name='camera',
            name='location',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='foxapp.location', verbose_name='Местоположение'),
        ),
    ]
