# Generated by Django 4.2.20 on 2025-05-01 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foxapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='survey',
        ),
        migrations.CreateModel(
            name='SurveyImageInt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foxapp.image', verbose_name='Изображение')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foxapp.survey', verbose_name='Исследование')),
            ],
            options={
                'verbose_name': 'Связь исследование-изображение',
                'verbose_name_plural': 'Связи исследование-изображение',
                'unique_together': {('survey', 'image')},
            },
        ),
        migrations.AddField(
            model_name='survey',
            name='images',
            field=models.ManyToManyField(related_name='surveys', through='foxapp.SurveyImageInt', to='foxapp.image', verbose_name='Изображения'),
        ),
    ]
